/**
 * package-mobile.mjs
 * -------------------
 * Packages CYRE Studio as an Android application through Capacitor.
 *
 * Validates the Capacitor configuration, ensures the web bundle exists, then
 * runs `capacitor sync android` and, when a JVM/Gradle toolchain is available,
 * `gradlew assembleDebug` to produce a real APK.
 *
 * When the Android toolchain is absent the script reports precisely what is
 * missing and exits non-zero rather than claiming an artifact exists.
 *
 * Usage:
 *   node studio/scripts/package-mobile.mjs [--check-only]
 */

import { execFileSync, spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const studioRoot = path.resolve(here, '..');
const repoRoot = path.resolve(studioRoot, '..');
const mobileDir = path.join(studioRoot, 'mobile');
const configPath = path.join(mobileDir, 'capacitor.config.json');

const checkOnly = process.argv.includes('--check-only');

function fail(message) {
  console.error(`\n✖ ${message}\n`);
  process.exit(1);
}

/* ------------------------------------------------------------ config check */

if (!fs.existsSync(configPath)) {
  fail(`No Capacitor config at ${path.relative(repoRoot, configPath)}.`);
}

let config;
try {
  config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
} catch (error) {
  fail(`Capacitor config is not valid JSON: ${error.message}`);
}

for (const key of ['appId', 'appName', 'webDir']) {
  if (!config[key] || String(config[key]).trim() === '') {
    fail(`Capacitor config is missing required key "${key}".`);
  }
}

if (!/^[a-z0-9_]+(\.[a-z0-9_]+)+$/i.test(config.appId)) {
  fail(`Capacitor appId "${config.appId}" is not a valid reverse-domain id.`);
}

const webDir = path.resolve(mobileDir, config.webDir);

console.log('✔ Capacitor configuration is valid');
console.log(`  app        : ${config.appName}`);
console.log(`  appId      : ${config.appId}`);
console.log(`  webDir     : ${path.relative(repoRoot, webDir)}`);

/* --------------------------------------------------------- toolchain check */

function has(command) {
  return spawnSync(command, ['-version'], { stdio: 'ignore' }).status === 0;
}

const javaPresent = has('java');
const androidHome = process.env.ANDROID_HOME || process.env.ANDROID_SDK_ROOT;

if (!javaPresent || !androidHome) {
  const missing = [];
  if (!javaPresent) missing.push('java (JDK 17+)');
  if (!androidHome) missing.push('ANDROID_HOME (Android SDK)');

  console.error(`\n✖ Android toolchain is not installed: ${missing.join(', ')}`);
  console.error('  Install a JDK and the Android SDK, export ANDROID_HOME, then run:');
  console.error('    pnpm --filter @cyre/studio-mobile add:android');
  console.error('    node studio/scripts/package-mobile.mjs');
  console.error('\n  The android/ project and APK are generated by those commands;');
  console.error('  neither exists yet, and no artifact was produced.\n');
  process.exit(checkOnly ? 0 : 1);
}

console.log('✔ Android toolchain present (java, ANDROID_HOME)');

if (checkOnly) {
  console.log('\n✔ Mobile packaging prerequisites satisfied (--check-only).');
  process.exit(0);
}

/* ------------------------------------------------------------------ build */

console.log('→ Building the web bundle Capacitor will host…');
try {
  execFileSync('node', [path.join(here, 'package-web.mjs')], {
    cwd: repoRoot,
    stdio: 'inherit',
  });
} catch {
  fail('Web bundle build failed; aborting mobile packaging.');
}

if (!fs.existsSync(path.join(webDir, 'index.html'))) {
  fail(`Expected the web bundle at ${path.relative(repoRoot, webDir)} but found no index.html.`);
}

const npxCapacitor = ['--yes', '@capacitor/cli@6'];
const androidDir = path.join(mobileDir, 'android');

if (!fs.existsSync(androidDir)) {
  console.log('→ Generating the Android project…');
  const add = spawnSync('npx', [...npxCapacitor, 'add', 'android'], {
    cwd: mobileDir,
    stdio: 'inherit',
  });
  if (add.status !== 0) fail('capacitor add android failed.');
}

console.log('→ Syncing the web bundle into the Android project…');
const sync = spawnSync('npx', [...npxCapacitor, 'sync', 'android'], {
  cwd: mobileDir,
  stdio: 'inherit',
});
if (sync.status !== 0) fail('capacitor sync android failed.');

console.log('→ Building the debug APK…');
const gradle = spawnSync('./gradlew', ['assembleDebug'], {
  cwd: androidDir,
  stdio: 'inherit',
});
if (gradle.status !== 0) fail('gradlew assembleDebug failed.');

const apkDir = path.join(androidDir, 'app', 'build', 'outputs', 'apk', 'debug');
if (!fs.existsSync(apkDir)) {
  fail(`Gradle reported success but produced no APK directory at ${path.relative(repoRoot, apkDir)}.`);
}

const apks = fs.readdirSync(apkDir).filter((file) => file.endsWith('.apk'));
if (apks.length === 0) {
  fail('Gradle produced no .apk artifact.');
}

console.log('\n✔ Android artifacts produced:');
for (const apk of apks) {
  const full = path.join(apkDir, apk);
  const bytes = fs.statSync(full).size;
  console.log(`  ${path.relative(repoRoot, full)} (${(bytes / 1024 / 1024).toFixed(2)} MiB)`);
}
