/**
 * Alert
 * ------
 * Represents a security alert generated by a monitoring system.
 * Tracks lifecycle from new to resolved/false positive.
 */

import { AlertStatus } from './AlertStatus.js';

export type AlertSeverity = 'info' | 'low' | 'medium' | 'high' | 'critical';

export interface AlertOptions {
  severity?: AlertSeverity;
  timestamp?: number;
  sourceId?: string;
  data?: Record<string, unknown>;
}

export class Alert {
  readonly id: string;
  readonly title: string;
  readonly description: string;
  readonly severity: AlertSeverity;
  readonly timestamp: number;
  readonly sourceId?: string;
  private status: AlertStatus;

  constructor(id: string, title: string, description: string, options: AlertOptions = {}) {
    if (!id || id.trim() === '') {
      throw new Error('Alert id must be a non-empty string.');
    }
    if (!title || title.trim() === '') {
      throw new Error('Alert title must be a non-empty string.');
    }
    if (!description || description.trim() === '') {
      throw new Error('Alert description must be a non-empty string.');
    }
    if (options.severity !== undefined) {
      const validSeverities: AlertSeverity[] = ['info', 'low', 'medium', 'high', 'critical'];
      if (!validSeverities.includes(options.severity)) {
        throw new Error(`Invalid alert severity: ${options.severity}`);
      }
    }
    if (options.timestamp !== undefined && !Number.isInteger(options.timestamp)) {
      throw new Error('Alert timestamp must be an integer if provided.');
    }
    if (options.sourceId !== undefined && options.sourceId.trim() === '') {
      throw new Error('Alert sourceId cannot be empty if provided.');
    }

    this.id = id;
    this.title = title;
    this.description = description;
    this.severity = options.severity ?? 'info';
    this.timestamp = options.timestamp ?? Date.now();
    this.sourceId = options.sourceId;
    this.status = AlertStatus.New;
  }

  getStatus(): AlertStatus {
    return this.status;
  }

  acknowledge(): void {
    if (this.status !== AlertStatus.New) {
      throw new Error(`Cannot acknowledge alert in status "${this.status}".`);
    }
    this.status = AlertStatus.Acknowledged;
  }

  startInvestigation(): void {
    if (this.status !== AlertStatus.Acknowledged && this.status !== AlertStatus.New) {
      throw new Error(`Cannot start investigation from status "${this.status}".`);
    }
    this.status = AlertStatus.Investigating;
  }

  contain(): void {
    if (this.status !== AlertStatus.Investigating) {
      throw new Error(`Cannot contain alert in status "${this.status}".`);
    }
    this.status = AlertStatus.Contained;
  }

  recover(): void {
    if (this.status !== AlertStatus.Contained) {
      throw new Error(`Cannot recover alert from status "${this.status}".`);
    }
    this.status = AlertStatus.Recovered;
  }

  resolve(): void {
    if (this.status === AlertStatus.Resolved || this.status === AlertStatus.FalsePositive) {
      throw new Error(`Alert already in final status "${this.status}".`);
    }
    this.status = AlertStatus.Resolved;
  }

  markFalsePositive(): void {
    if (this.status === AlertStatus.Resolved || this.status === AlertStatus.FalsePositive) {
      throw new Error(`Alert already in final status "${this.status}".`);
    }
    this.status = AlertStatus.FalsePositive;
  }

  toJSON(): Record<string, unknown> {
    return {
      id: this.id,
      title: this.title,
      description: this.description,
      severity: this.severity,
      timestamp: this.timestamp,
      sourceId: this.sourceId,
      status: this.status,
    };
  }
}
